trigger:
- play-lingua

variables:
  backendDirName: 'server'
  frontDirName: 'client'

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    maxParallel: 2    
    matrix:
      Release:
        configuration: release
  steps:
  - task: DotNetCoreInstaller@0
    inputs:
      packageType: 'sdk' 
      version: '2.2.100' 

  - script: 'npm --prefix ./$(frontDirName) install ./$(frontDirName)'
    displayName: Client - installation

  - script: 'npm run build:prod --prefix ./$(frontDirName)'
    displayName: Client - Build        

  - script: 'dotnet clean $(backendDirName)/PlayLingua.Server.sln'
    displayName: Server - Clean

  - script: 'dotnet build $(backendDirName)/PlayLingua.Server.sln'
    displayName: Server - Build

  - script: 'dotnet test $(backendDirName)'
    displayName: Server - Test




