<<<<<<< HEAD
=======
# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

>>>>>>> 852cc03c63860fe87e4c08ec3100673566763dc2
name: Angular

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
<<<<<<< HEAD
        
        node-version: '12'
        - name: Install dependencies

        run: npm install
        working-directory: client
        - name: Run unit tests

        run: npm run test:prod
        working-directory: client
        - name: Build code

        run: npm run build:prod
        working-directory: client
=======
        node-version: '12'
    - name: Install dependencies
      run: npm install
      working-directory: client
>>>>>>> 852cc03c63860fe87e4c08ec3100673566763dc2
