name: Deploy to production

on:
  push:
    branches:
      - "main"

env:
  AZURE_WEBAPP_NAME: play-lingua
  AZURE_WEBAPP_PACKAGE_PATH: 'deployed-directory'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '3.1'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - uses: actions/checkout@v2
      
      # Setup nodejs
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: "12"
          
      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: npm ci
        working-directory: client

      # Run dotnet build and publish
      - name: front end build
        run: npm run build:prod
        working-directory: client
        
      # Run dotnet build and publish
      - name: dotnet build and publish
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
        working-directory: server
        
      # Deploy to Azure Web apps
      - name: 'Azure webapp deploy'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
          package: 'server/${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
